### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by ultrono** [BKWLD/cloner#26]
Are you planning to support Laravel 6?

**Comment by weotch** [comment]
Probably not in the short term but happy to take PRs or add a new maintainer if someone wants to contribute.

**Comment by djoudi** [comment]
i try to upgrade it :)

**Comment by ihorvorotnov** [comment]
I just bumped version constraints in both cloner and upchuck packages, pointed composer to my forks and was able to upgrade to Laravel 6. However, some updates in tests were required as well. 

I use cloner in Laravel Nova to handle resource cloning, tested here and there - seems to work perfectly fine with L6.

**Comment by ultrono** [comment]
> I just bumped version constraints in both cloner and upchuck packages, pointed composer to my forks and was able to upgrade to Laravel 6. However, some updates in tests were required as well.
> 
> I use cloner in Laravel Nova to handle resource cloning, tested here and there - seems to work perfectly fine with L6.

Spot on, I'm looking at https://github.com/ihorvorotnov/cloner/commits/master. 

it may be worth specifying versions restraints like https://github.com/owen-it/laravel-auditing/blob/master/composer.json#L42-L46 - this way you can allow version 5.8 and 6.0.

It a shame that forks are required for smaller packages like this, as Laravel 6 is a LTS release.

I guess for the time being forks are required :(

**Comment by ihorvorotnov** [comment]
@ultrono Yeah, I used most recent versions just to test whether it'll work with L6 out of the box, without any actual code changes. Went through L6 upgrade guide and checked for usage of changed methods etc - didn't find anything within the package code so I'm assuming it's a matter of versions bump only. 

Giving it another day or two for my editors to test the cloning functionality on a real project, if anything goes wrong - they'll let me know. If not - will update versions with alternatives and submit PRs to both packages.

Worth mentioning that tests are actually broken (apart from using long deprecated `PHPUnit_Framework_TestCase`), but there's a separate issue/PR trying to address this so I'll probably skip it in my PRs.

Also, one more thing - the package uses (https://packagist.org/packages/satooshi/php-coveralls)[satooshi/php-coveralls] which is deprecated and should be replaced with (https://packagist.org/packages/php-coveralls/php-coveralls)[php-coveralls/php-coveralls]. However, that should be handled in a separate PR I believe.

**Comment by djoudi** [comment]
#27

**Comment by ultrono** [comment]
> @ultrono Yeah, I used most recent versions just to test whether it'll work with L6 out of the box, without any actual code changes. Went through L6 upgrade guide and checked for usage of changed methods etc - didn't find anything within the package code so I'm assuming it's a matter of versions bump only.
> 
> Giving it another day or two for my editors to test the cloning functionality on a real project, if anything goes wrong - they'll let me know. If not - will update versions with alternatives and submit PRs to both packages.
> 
> Worth mentioning that tests are actually broken (apart from using long deprecated `PHPUnit_Framework_TestCase`), but there's a separate issue/PR trying to address this so I'll probably skip it in my PRs.
> 
> Also, one more thing - the package uses (outdated) [satooshi/php-coveralls](https://packagist.org/packages/satooshi/php-coveralls) which is deprecated and should be replaced with [php-coveralls/php-coveralls](https://packagist.org/packages/php-coveralls/php-coveralls). However, that should be handled in a separate PR too I believe.

Great stuff. Have just pulled down your updates into a vanilla Laravel 6 project. Cloning simple models and models with multiple relations worked great 👍

**Comment by weotch** [comment]
I released this as  3.5.0, thanks @djoudi.

Also, if anyone wants to get involved as a maintainer, lemme know and I'll add you to the project.

**Comment by denisdulici** [comment]
@weotch it seems you forgot to merge the pr https://github.com/BKWLD/cloner/pull/27

**Comment by ultrono** [comment]
Actually, not sure of it's just, myself but I can't see the changes on packagist or one the main repo screen. i.e. https://github.com/BKWLD/cloner/blob/master/composer.json#L13 vs Laravel 6 support from #27 at https://github.com/BKWLD/cloner/blob/f53a74e09d1f95ffed8bfab0b1ef0ce5784bbf4c/composer.json#L13

**Comment by djoudi** [comment]
i don't see the change at 3.5.0 release
